"""rename image to image_url

Revision ID: 8efa52632b6d
Revises: 2c344e0cc7ef
Create Date: 2024-02-08 11:35:45.061694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efa52632b6d'
down_revision = '2c344e0cc7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        # batch_op.drop_column('image')
        batch_op.alter_column("image", new_column_name="image_url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))
        # batch_op.drop_column('image_url')
        batch_op.alter_column("image_url", new_column_name="image")

    # ### end Alembic commands ###
