"""rename image_url to image

Revision ID: 67946dedac8c
Revises: 8efa52632b6d
Create Date: 2024-02-08 12:00:05.874904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67946dedac8c'
down_revision = '8efa52632b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        # batch_op.drop_column('image_url')
        batch_op.alter_column("image_url", new_column_name="image")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        # batch_op.drop_column('image')
        batch_op.alter_column("image", new_column_name="image_url")

    # ### end Alembic commands ###
